=== BelledonneCommunications/flexisip/test_deprecated/sipp.dtd
<!ELEMENT Global (action)? >
<!ATTLIST Global variables CDATA #IMPLIED >

<!ELEMENT nop (action)+ >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT action ( ereg | assign | assignstr | add | exec)+ >


<!ELEMENT exec EMPTY >
<!ATTLIST exec play_pcap_audio CDATA #REQUIRED >

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg header NMTOKEN #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|hdr) "msg" >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED >
<!ATTLIST add value CDATA #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED >
<!ATTLIST assign value CDATA #REQUIRED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv crlf NMTOKEN #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv response NMTOKEN #IMPLIED >
<!ATTLIST recv request NMTOKEN #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv rtd (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv start_rtd (true|false) #IMPLIED >
<!ATTLIST recv timeout CDATA #IMPLIED >

<!ELEMENT scenario ( Global | nop | CallLengthRepartition | ResponseTimeRepartition | pause | recv | send )* >
<!ATTLIST scenario name CDATA #REQUIRED >

<!ELEMENT send ( #PCDATA ) >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send rtd (true|false) #IMPLIED >
<!ATTLIST send start_rtd (true|false) #IMPLIED >

=== BelledonneCommunications/flexisip/test/invites/invite.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "../sipp.dtd">

<scenario>

<Global variables="userId,luserAdd,luserIpPort">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop>
  <action>
    <add assign_to="userId" value="1" />
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />   
    <assignstr assign_to="luserAdd" value="sip:user0.000000@sip.example.org" />   
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@sip.example.org" /> 
  </action>
</nop>


  <send>
    <![CDATA[

      INVITE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Test invite from client
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="180" optional="true"></recv>
  <recv response="183" optional="true"></recv>
  <recv response="200" rtd="true" timeout="2000"></recv>


  <send>
    <![CDATA[

      ACK [$ruserAdd]:5063 SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Ack user we have received the 200
      Content-Length: 0

    ]]>
  </send>


  <pause/>

  <send>
    <![CDATA[

      BYE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: [$luserAdd]
      [authentication username=user0.000000 password=user0.000000]
      Max-Forwards: 70
      Subject: Teminate invite
      Content-Length: 0

    ]]>
  </send>


  <recv response="200" crlf="true" timeout="2000"></recv>

  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== BelledonneCommunications/flexisip/test/register_users.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Register one user without authentication">

<Global variables="userId,luserAddContact,luserIpPort">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop hide="true">
  <action>
    <add assign_to="userId" value="1" /> <!-- strangely, now userId=1.000000-->
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />
    <assignstr assign_to="luserAddContact" value="sip:user[$userId]@[local_ip]:5063" />
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@sip.example.org" />
  </action>
</nop>


  <send>
    <![CDATA[
    REGISTER sip:[remote_ip] SIP/2.0
	Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
	From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
	To: [$ruserAdd]
	Call-ID: [call_id]
	CSeq: 1 REGISTER
	Contact: [$luserAddContact]
	Max-Forwards: 70
	User-Agent: Linphone/Linphone-3.3.x (sipp/unknown)
	Expires: 3600
	Content-Length: 0
    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="200"></recv>

  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>
</scenario>

=== BelledonneCommunications/flexisip/test/relaying/invite.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "../sipp.dtd">

<scenario>

<Global variables="userId,luserAdd,luserIpPort">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop>
  <action>
    <add assign_to="userId" value="1" />
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />   
    <assignstr assign_to="luserAdd" value="sip:[$luserIpPort]" />   
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@sip.example.org" /> 
  </action>
</nop>



  <send>
    <![CDATA[

      INVITE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Test invite from client
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=A conversation
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 8
      b=AS:75
      a=rtpmap:8 PCMA/8000/1
      a=ptime:30
      a=sendrecv

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="180" optional="true"></recv>
  <recv response="183" optional="true"></recv>
  <recv response="200" rtd="true" timeout="2000"></recv>


  <send>
    <![CDATA[

      ACK [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Ack user we have received the 200
      Content-Length: 0

    ]]>
  </send>


  <nop>
    <action>
      <exec play_pcap_audio="relaying/one_way_pcma_capture.pcap"/>
    </action>
  </nop>

  <!-- Wait untill the pcap file is almost entirely played. -->
  <pause milliseconds="180000"/>

  <!-- The 'crlf' option inserts a blank line in the statistics report. -->
  <send retrans="5">
    <![CDATA[

      BYE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Teminate invite
      Content-Length: 0

    ]]>
  </send>


  <recv response="200" crlf="true" timeout="2000"></recv>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== BelledonneCommunications/flexisip/test_deprecated/register_inviter-auth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario>

<Global variables="luserAdd,domain,ua,expire,auth,luserIpPort">
</Global>


<nop hide="true">
  <action>
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />   
    <assignstr assign_to="luserAdd" value="sip:[$luserIpPort]" />   
    <assignstr assign_to="ruserAdd" value="sip:user0.000000@[$domain]" /> 
  </action>
</nop>
  

<send>
  <![CDATA[
  REGISTER sip:[remote_ip] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
      To: [$ruserAdd]
      Call-ID: [call_id]
      CSeq: 1 REGISTER
      Contact: [$luserAdd]
      Max-Forwards: 70
      User-Agent: [$ua]
      Expires: [$expire]
      Content-Length: 0
  ]]>
</send>

<recv response="100" optional="true"></recv>
<recv response="401" auth="true"></recv>

<send>
  <![CDATA[
  REGISTER sip:[remote_ip] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
      To: [$ruserAdd]
      Call-ID: [call_id]
      CSeq: 2 REGISTER
      Contact: [$luserAdd]
      [authentication username=user0.000000 password=user0.000000]
      Max-Forwards: 70
      User-Agent: [$ua]
      Expires: 3600
      Content-Length: 0
  ]]>
</send>

<recv response="100" optional="true"></recv>
<recv response="200"></recv>


<ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
<CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>
</scenario>

=== BelledonneCommunications/flexisip/test_deprecated/multi/register_multi_noauth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Register one user with 10 contacts without authentication">

<Global variables="userId,luserIpPort,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop hide="true">
  <action>
    <add assign_to="userId" value="1" /> <!-- strangely, now userId=1.000000-->
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@sip.example.org" />
    <assignstr assign_to="m1" value="<sip:user1@[local_ip]:5063;line=79654655646546;transport=udp>;expires=2000;q=1.5" />
    <assignstr assign_to="m2" value="sip:user2@[local_ip]:5063" />
    <assignstr assign_to="m3" value="sip:user3@[local_ip]:5063" />
    <assignstr assign_to="m4" value="sip:user4@[local_ip]:5063" />
    <assignstr assign_to="m5" value="sip:user5@[local_ip]:5063" />
    <assignstr assign_to="m6" value="sip:user6@[local_ip]:5063" />
    <assignstr assign_to="m7" value="sip:user7@[local_ip]:5063" />
    <assignstr assign_to="m8" value="sip:user8@[local_ip]:5063" />
    <assignstr assign_to="m9" value="sip:user9@[local_ip]:5063" />
    <assignstr assign_to="m10" value="sip:user10@[local_ip]:5063" />
  </action>
</nop>


  <send>
    <![CDATA[
    REGISTER sip:[remote_ip] SIP/2.0
	Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
	From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
	To: [$ruserAdd]
	Call-ID: [call_id]
	CSeq: 1 REGISTER
	Contact: [$m1],[$m2],[$m3],[$m4],[$m5],[$m6],[$m7],[$m8],[$m9],[$m10]
	Max-Forwards: 70
	User-Agent: Linphone/Linphone-3.3.x (sipp/unknown)
	Expires: 3600
	Content-Length: 0
    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="200"></recv>

  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>
</scenario>

=== BelledonneCommunications/flexisip/test_deprecated/message/invite-auth.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "../sipp.dtd">

<scenario>

<Global variables="userId,luserAdd,domain,ua,luserIpPort">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop>
  <action>
    <add assign_to="userId" value="1" />
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />   
    <assignstr assign_to="luserAdd" value="sip:user0.000000@[$domain]" />
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@[$domain]" /> 
  </action>
</nop>


  <send>
    <![CDATA[

      MESSAGE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      User-Agent: [$ua]
      CSeq: 1 MESSAGE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Content-Type: text/plain
      Content-Length: [len]

      Hello World user[$userId]!

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="407" auth="true" timeout="2000"></recv>

  <send>
    <![CDATA[

      MESSAGE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      User-Agent: [$ua]
      CSeq: 2 MESSAGE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Content-Type: text/plain
      Content-Length: [len]
      [field0]

      Hello World user[$userId]!

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="200" rtd="true" timeout="2000"></recv>


  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== BelledonneCommunications/flexisip/test_deprecated/register_users-auth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Register one user with authentication">

<Global variables="userId,luserIpPort,domain,ua,expire">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop hide="true">
  <action>
    <add assign_to="userId" value="1" /> <!-- strangely, now userId=1.000000-->
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />
    <assignstr assign_to="luserAddContact" value="sip:user[$userId]@[local_ip]:5063" />
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@[$domain]" />
  </action>
</nop>


  <send>
    <![CDATA[
    REGISTER sip:[remote_ip] SIP/2.0
	Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
	From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
	To: [$ruserAdd]
	Call-ID: [call_id]
	CSeq: 1 REGISTER
	Contact: [$luserAddContact]
	Max-Forwards: 70
	User-Agent: [$ua]
	Expires: [$expire]
	Content-Length: 0
    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="401" auth="true"></recv>


  <send>
    <![CDATA[
    REGISTER sip:[remote_ip] SIP/2.0
        Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
        From: [$ruserAdd];tag=[pid]SIPpTag00[call_number]
        To: [$ruserAdd]
        Call-ID: [call_id]
        CSeq: 2 REGISTER
        Contact: [$luserAddContact]
        [field0]
        Max-Forwards: 70
        User-Agent: [$ua]
        Expires: [$expire]
        Content-Length: 0
    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="200"></recv>

  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>
</scenario>

=== BelledonneCommunications/flexisip/test/chained/invite.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "../sipp.dtd">

<scenario>

<Global variables="userId,luserAdd,luserIpPort,authentify">
  <action>
    <assign assign_to="userId" value="0" />
  </action>
</Global>

<nop>
  <action>
    <assignstr assign_to="luserIpPort" value="[local_ip]:[local_port]" />   
    <assignstr assign_to="luserAdd" value="sip:user0.000000@sip.example.org" />   
    <add assign_to="userId" value="1" />
    <assignstr assign_to="ruserAdd" value="sip:user[$userId]@sip.example.org" /> 
  </action>
</nop>



  <send>
    <![CDATA[

      INVITE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Test invite from client
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="407" optional="true" auth="true" next="2"></recv>
  <recv response="180" optional="true"></recv>
  <recv response="183" optional="true"></recv>
  <recv response="200" rtd="true" timeout="2000"></recv>

  <nop condexec="authentify" hide="true">
   <action>
    <log message="Scenario expecting authentication but server sent a 200 OK to an unauthenticated registrar (scn authentication = [$authentify])"/>
    <exec command="aplay ../bom.wav" />
   </action>
  </nop>

  <nop next="3" hide="true" />

  <label id="2"/>
  <nop condexec="authentify" condexec_inverse="true" hide="true">
   <action>
    <log message="Scenario doesn't expect authentication but server sent a 407 to the unauthenticated registrar (scn authentication = [$authentify])"/>
    <exec command="aplay ../bom.wav" />
   <jump value="3"/>
   </action>
  </nop>

  <send>
    <![CDATA[

      INVITE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>
      Call-ID: [call_id]
      CSeq: 2 INVITE
      Contact: [$luserAdd]
      [authentication username=user0.000000 password=user0.000000]
      Max-Forwards: 70
      Subject: Test invite from client
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true"></recv>
  <recv response="180" optional="true"></recv>
  <recv response="183" optional="true"></recv>
  <recv response="200" rtd="true" timeout="2000"></recv>



  <send>
    <![CDATA[

      ACK [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: [$luserAdd]
      Max-Forwards: 70
      Subject: Ack user we have received the 200
      Content-Length: 0

    ]]>
  </send>

  <!-- This delay can be customized by the -d command-line option       -->
  <!-- or by adding a 'milliseconds = "value"' option here.             -->
  <pause/>

  <!-- The 'crlf' option inserts a blank line in the statistics report. -->
  <send>
    <![CDATA[

      BYE [$ruserAdd] SIP/2.0
      Via: SIP/2.0/[transport] [$luserIpPort];branch=[branch]
      From: <[$luserAdd]>;tag=[pid]SIPpTag00[call_number]
      To: <[$ruserAdd]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: [$luserAdd]
      [authentication username=user0.000000 password=user0.000000]
      Max-Forwards: 70
      Subject: Teminate invite
      Content-Length: 0

    ]]>
  </send>


  <recv response="200" crlf="true" timeout="2000"></recv>

  <label id="3"/>



  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>
